spring:
  application:
    name: ze-parceiros
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:ze-delivery}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
